name: fitlifebuddy
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  data_table_2: ^2.5.9
  path_provider: ^2.1.1
  isar: ^3.1.0+1
  equatable: ^2.0.5
  toastification: ^1.2.1
  http: ^1.1.0
  intl: ^0.19.0
  dropdown_button2: ^2.3.9
  easy_date_timeline: ^1.0.6
  unsplash_client: ^2.2.0
  shared_preferences: ^2.2.3
  responsive_framework: ^1.4.0
  easy_loading_button: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/languages/